background = #080604
foreground = #ffffff
background-opacity = 0.4

cursor-color = #f0a010
cursor-text = #080604

selection-background = #f0a010
selection-foreground = #080604

palette = 0=#1a1208
palette = 1=#c85018
palette = 2=#a6e3a1
palette = 3=#f0a010
palette = 4=#89b4fa
palette = 5=#e07030
palette = 6=#2a7870
palette = 7=#bac2de
palette = 8=#585b70
palette = 9=#c85018
palette = 10=#a6e3a1
palette = 11=#f0a010
palette = 12=#3a4a80
palette = 13=#e07030
palette = 14=#2a7870
palette = 15=#ffffff
palette = 16=#e07030
palette = 17=#f0a010
