[[track]]
path = "/home/berni/Music/中文/Coco Elva Tia [JXb04PcA7rg].mp3"
title = "Coco Elva Tia [JXb04PcA7rg]"

[[track]]
path = "/home/berni/Music/中文/Illusionary Daytime (幻奏 Remix) [hATE0C4aQqw].mp3"
title = "Illusionary Daytime (幻奏 Remix) [hATE0C4aQqw]"
duration_secs = 130

[[track]]
path = "/home/berni/Music/中文/Jumping Machine (跳楼机) [TOC78RUj8pg].mp3"
title = "Jumping Machine (跳楼机) [TOC78RUj8pg]"
duration_secs = 201

[[track]]
path = "/home/berni/Music/中文/Love Can...... [ldF57rxmRpQ].mp3"
title = "Love Can...... [ldF57rxmRpQ]"
duration_secs = 261

[[track]]
path = "/home/berni/Music/中文/Marry Me Today [6UlVEo7d6HA].mp3"
title = "Marry Me Today [6UlVEo7d6HA]"
duration_secs = 272

[[track]]
path = "/home/berni/Music/中文/No More [EOkzJ6tzP0g].mp3"
title = "No More [EOkzJ6tzP0g]"

[[track]]
path = "/home/berni/Music/中文/Storm [TaLDsEcf6Sk].mp3"
title = "Storm [TaLDsEcf6Sk]"

[[track]]
path = "/home/berni/Music/中文/Why Are You With Me, My Love [cZyEv9AlR-k].mp3"
title = "Why Are You With Me, My Love [cZyEv9AlR-k]"

[[track]]
path = "/home/berni/Music/中文/Wo Ke Yi [Poy4AhZLIWo].mp3"
title = "Wo Ke Yi [Poy4AhZLIWo]"

[[track]]
path = "/home/berni/Music/中文/一点点 (DJ版) [Ke-xD5_3tGY].mp3"
title = "一点点 (DJ版) [Ke-xD5_3tGY]"

[[track]]
path = "/home/berni/Music/中文/一点点（为什么晚上总是有星星） [s6Yc9yc7emA].mp3"
title = "一点点（为什么晚上总是有星星） [s6Yc9yc7emA]"

[[track]]
path = "/home/berni/Music/中文/不醉不會 [ohoeAKGx9SE].mp3"
title = "不醉不會 [ohoeAKGx9SE]"

[[track]]
path = "/home/berni/Music/中文/人间天堂 [kJBjldub6x4].mp3"
title = "人间天堂 [kJBjldub6x4]"

[[track]]
path = "/home/berni/Music/中文/代替 [LjmlteROZHk].mp3"
title = "代替 [LjmlteROZHk]"
duration_secs = 234

[[track]]
path = "/home/berni/Music/中文/任夏 - 算了吧『當別人問起想你嗎會後悔吧，我的眼淚還是會落下。』【動態歌詞 ｜ Pinyin Lyrics】【PENGUIN MUSIC】 [IGFOHxOJK34].mp3"
title = "算了吧『當別人問起想你嗎會後悔吧，我的眼淚還是會落下。』【動態歌詞 ｜ Pinyin Lyrics】【PENGUIN MUSIC】 [IGFOHxOJK34]"
artist = "任夏"

[[track]]
path = "/home/berni/Music/中文/你就不要想起我 [CrSCaW-k-fs].mp3"
title = "你就不要想起我 [CrSCaW-k-fs]"

[[track]]
path = "/home/berni/Music/中文/你的影子 [hVcmVl9b2Xg].mp3"
title = "你的影子 [hVcmVl9b2Xg]"

[[track]]
path = "/home/berni/Music/中文/傷心的人別聽慢歌 [abz1pNrClkM].mp3"
title = "傷心的人別聽慢歌 [abz1pNrClkM]"

[[track]]
path = "/home/berni/Music/中文/其实 [TWHy8Iw6aiI].mp3"
title = "其实 [TWHy8Iw6aiI]"

[[track]]
path = "/home/berni/Music/中文/加油卡(Swipe That Gas) [A2ZCJi9chjw].mp3"
title = "加油卡(Swipe That Gas) [A2ZCJi9chjw]"

[[track]]
path = "/home/berni/Music/中文/反正结局都一样 [LBDq1an1nN8].mp3"
title = "反正结局都一样 [LBDq1an1nN8]"

[[track]]
path = "/home/berni/Music/中文/可我只是海 [I3qbRMNC-54].mp3"
title = "可我只是海 [I3qbRMNC-54]"

[[track]]
path = "/home/berni/Music/中文/向思思 - 總會有人『總會有人把你看得比自己更重要，會有人發現你身上所有的好。』【動態歌詞 ｜ Pinyin Lyrics】【PENGUIN MUSIC】 [rE_OF-NxmCI].mp3"
title = "總會有人『總會有人把你看得比自己更重要，會有人發現你身上所有的好。』【動態歌詞 ｜ Pinyin Lyrics】【PENGUIN MUSIC】 [rE_OF-NxmCI]"
artist = "向思思"

[[track]]
path = "/home/berni/Music/中文/因果(Karma Code) [eVHhVuIYT6k].mp3"
title = "因果(Karma Code) [eVHhVuIYT6k]"

[[track]]
path = "/home/berni/Music/中文/在眼前 [J4L05tNopEI].mp3"
title = "在眼前 [J4L05tNopEI]"

[[track]]
path = "/home/berni/Music/中文/多遠都要在一起 [KVVsS1j0kpg].mp3"
title = "多遠都要在一起 [KVVsS1j0kpg]"

[[track]]
path = "/home/berni/Music/中文/大展鴻圖(Blueprint Supreme) [yWT-UopFlAs].mp3"
title = "大展鴻圖(Blueprint Supreme) [yWT-UopFlAs]"

[[track]]
path = "/home/berni/Music/中文/大眠 [SW3ZPpysn0o].mp3"
title = "大眠 [SW3ZPpysn0o]"

[[track]]
path = "/home/berni/Music/中文/天若有情 [WYUnRcE2CsY].mp3"
title = "天若有情 [WYUnRcE2CsY]"

[[track]]
path = "/home/berni/Music/中文/如果可以·2023 [xaz5yYea4ys].mp3"
title = "如果可以·2023 [xaz5yYea4ys]"

[[track]]
path = "/home/berni/Music/中文/字字句句 [C5CvN3EmOB4].mp3"
title = "字字句句 [C5CvN3EmOB4]"

[[track]]
path = "/home/berni/Music/中文/室内系的TrackMaker (Melodic Minor版) [TsDMejm-HoY].mp3"
title = "室内系的TrackMaker (Melodic Minor版) [TsDMejm-HoY]"

[[track]]
path = "/home/berni/Music/中文/寂寞烟火 [6U_v5p8SyW4].mp3"
title = "寂寞烟火 [6U_v5p8SyW4]"

[[track]]
path = "/home/berni/Music/中文/小幸运 (费烟催泪版0.98X) [MNesU88_dAs].mp3"
title = "小幸运 (费烟催泪版0.98X) [MNesU88_dAs]"

[[track]]
path = "/home/berni/Music/中文/小手拉大手 [mh0uiWlr4RE].mp3"
title = "小手拉大手 [mh0uiWlr4RE]"

[[track]]
path = "/home/berni/Music/中文/小船 [iBaHt7wVx2I].mp3"
title = "小船 [iBaHt7wVx2I]"

[[track]]
path = "/home/berni/Music/中文/張快玉 - 室內系的TrackMaker「高峰期的街上 堆滿車子 長長的一隊堵塞max」【動態歌詞⧸PinyinLyrics】♪ [QK52ns4siqE].mp3"
title = "室內系的TrackMaker「高峰期的街上 堆滿車子 長長的一隊堵塞max」【動態歌詞⧸PinyinLyrics】♪ [QK52ns4siqE]"
artist = "張快玉"

[[track]]
path = "/home/berni/Music/中文/心跳 [1kUYKhbpTRc].mp3"
title = "心跳 [1kUYKhbpTRc]"

[[track]]
path = "/home/berni/Music/中文/念慈菴(Nin Jiom) [LfkWXhpUBzY].mp3"
title = "念慈菴(Nin Jiom) [LfkWXhpUBzY]"

[[track]]
path = "/home/berni/Music/中文/想自由 [-ELNc1_cMvA].mp3"
title = "想自由 [-ELNc1_cMvA]"

[[track]]
path = "/home/berni/Music/中文/愛我別走 [b4dlmN7k8-Y].mp3"
title = "愛我別走 [b4dlmN7k8-Y]"

[[track]]
path = "/home/berni/Music/中文/是想你的声音啊 (DJ版) [nvHH-0rnLyI].mp3"
title = "是想你的声音啊 (DJ版) [nvHH-0rnLyI]"

[[track]]
path = "/home/berni/Music/中文/是想你的声音啊 [0oNSHSRZNS0].mp3"
title = "是想你的声音啊 [0oNSHSRZNS0]"

[[track]]
path = "/home/berni/Music/中文/最初的记忆·2023 [_mSoIdx30qc].mp3"
title = "最初的记忆·2023 [_mSoIdx30qc]"
duration_secs = 199

[[track]]
path = "/home/berni/Music/中文/最后一页 [UDyhT-6Idek].mp3"
title = "最后一页 [UDyhT-6Idek]"

[[track]]
path = "/home/berni/Music/中文/李荣浩Ronghao Li 《不遗憾》【“你的婚礼” 电影主题曲】动态歌词⧸Lyrics Video [n_KHQk1w7Gs].mp3"
title = "李荣浩Ronghao Li 《不遗憾》【“你的婚礼” 电影主题曲】动态歌词⧸Lyrics Video [n_KHQk1w7Gs]"

[[track]]
path = "/home/berni/Music/中文/江美琪 Maggie Chiang - 雙手的溫柔 Gentleness Of Both Hands (官方完整版MV) [RPzYWnJ5RvY].mp3"
title = "雙手的溫柔 Gentleness Of Both Hands (官方完整版MV) [RPzYWnJ5RvY]"
artist = "江美琪 Maggie Chiang"

[[track]]
path = "/home/berni/Music/中文/海屿你 (破碎版) [tmMemGAPTHI].mp3"
title = "海屿你 (破碎版) [tmMemGAPTHI]"

[[track]]
path = "/home/berni/Music/中文/渐冷 [rZCTXNioPOk].mp3"
title = "渐冷 [rZCTXNioPOk]"

[[track]]
path = "/home/berni/Music/中文/爱随你飞而我追 [dbn3QOPXtsk].mp3"
title = "爱随你飞而我追 [dbn3QOPXtsk]"

[[track]]
path = "/home/berni/Music/中文/真的没喝多 [__hmZ1KxcMs].mp3"
title = "真的没喝多 [__hmZ1KxcMs]"

[[track]]
path = "/home/berni/Music/中文/私奔到月球 [JsOQLET3Z4k].mp3"
title = "私奔到月球 [JsOQLET3Z4k]"

[[track]]
path = "/home/berni/Music/中文/突然好想你 [EopCPbEj1FA].mp3"
title = "突然好想你 [EopCPbEj1FA]"

[[track]]
path = "/home/berni/Music/中文/红昭愿 (DJ于成龙) [PcwFG1Mrme4].mp3"
title = "红昭愿 (DJ于成龙) [PcwFG1Mrme4]"

[[track]]
path = "/home/berni/Music/中文/蔡健雅-紅色高跟鞋『你像窝在被子里的舒服』【動態歌詞Lyrics】 [ATblV50Odx8].mp3"
title = "蔡健雅-紅色高跟鞋『你像窝在被子里的舒服』【動態歌詞Lyrics】 [ATblV50Odx8]"

[[track]]
path = "/home/berni/Music/中文/起风了 [CKs06juUk6E].mp3"
title = "起风了 [CKs06juUk6E]"

[[track]]
path = "/home/berni/Music/中文/还是会想你 (DJ铁柱版) [lefUZjAUVEI].mp3"
title = "还是会想你 (DJ铁柱版) [lefUZjAUVEI]"

[[track]]
path = "/home/berni/Music/中文/遐想 [7r_g40NRA_U].mp3"
title = "遐想 [7r_g40NRA_U]"

[[track]]
path = "/home/berni/Music/中文/遗落 [TnxuPMU9K1Q].mp3"
title = "遗落 [TnxuPMU9K1Q]"

[[track]]
path = "/home/berni/Music/中文/错季 (加速版) [6GY3BgWfs2M].mp3"
title = "错季 (加速版) [6GY3BgWfs2M]"

[[track]]
path = "/home/berni/Music/中文/错季 [e6fMs-6HY-s].mp3"
title = "错季 [e6fMs-6HY-s]"

[[track]]
path = "/home/berni/Music/中文/雪二 《漸冷》｜ cover 高芸歆 ｜ MxA Music [D2Vpm7WKn5A].mp3"
title = "雪二 《漸冷》｜ cover 高芸歆 ｜ MxA Music [D2Vpm7WKn5A]"

[[track]]
path = "/home/berni/Music/中文/雪藏 (加速版) [W_cvcGjf-D8].mp3"
title = "雪藏 (加速版) [W_cvcGjf-D8]"

[[track]]
path = "/home/berni/Music/中文/雪藏 [U5O9leHFIdc].mp3"
title = "雪藏 [U5O9leHFIdc]"

[[track]]
path = "/home/berni/Music/中文/鶴立雞群(Rare One) [Oxi1VaUib9o].mp3"
title = "鶴立雞群(Rare One) [Oxi1VaUib9o]"
