[[track]]
path = "/home/berni/Music/dj/All Eyes On Me [9HeiBJ5mgtA].mp3"
title = "All Eyes On Me [9HeiBJ5mgtA]"

[[track]]
path = "/home/berni/Music/dj/Bricks [tP_J1i2J-2g].mp3"
title = "Bricks [tP_J1i2J-2g]"

[[track]]
path = "/home/berni/Music/dj/CD is dead [lyPIJRvRKZ0].mp3"
title = "CD is dead [lyPIJRvRKZ0]"

[[track]]
path = "/home/berni/Music/dj/Call Me Babe [Yi_dqJ2W-UM].mp3"
title = "Call Me Babe [Yi_dqJ2W-UM]"

[[track]]
path = "/home/berni/Music/dj/Ear Candy (One Day no.2) [ZUDd96OPZWQ].mp3"
title = "Ear Candy (One Day no.2) [ZUDd96OPZWQ]"

[[track]]
path = "/home/berni/Music/dj/Forbidden Voices [_eIJZ9_JsVk].mp3"
title = "Forbidden Voices [_eIJZ9_JsVk]"

[[track]]
path = "/home/berni/Music/dj/Funk Tribu - Platinum [TT04] [enAl9gOlM7M].mp3"
title = "Platinum [TT04] [enAl9gOlM7M]"
artist = "Funk Tribu"

[[track]]
path = "/home/berni/Music/dj/Gucci [liKgsNLBfmM].mp3"
title = "Gucci [liKgsNLBfmM]"

[[track]]
path = "/home/berni/Music/dj/Henry Hoover (feat. MC ShOrty B.) [f_g4hEuSxoE].mp3"
title = "Henry Hoover (feat. MC ShOrty B.) [f_g4hEuSxoE]"

[[track]]
path = "/home/berni/Music/dj/I Feel [gPawXJeb7D0].mp3"
title = "I Feel [gPawXJeb7D0]"

[[track]]
path = "/home/berni/Music/dj/IS U CHEMICAL？ [Lo6O4klwlDY].mp3"
title = "IS U CHEMICAL？ [Lo6O4klwlDY]"

[[track]]
path = "/home/berni/Music/dj/Knowledge is a weapon [QHi6SVJf2Fk].mp3"
title = "Knowledge is a weapon [QHi6SVJf2Fk]"

[[track]]
path = "/home/berni/Music/dj/LAMBORGHINI [3Tmn7AX-fM0].mp3"
title = "LAMBORGHINI [3Tmn7AX-fM0]"

[[track]]
path = "/home/berni/Music/dj/Make You Trip [0ubWiOqJMFU].mp3"
title = "Make You Trip [0ubWiOqJMFU]"

[[track]]
path = "/home/berni/Music/dj/Nasty [WV53GyfJN0M].mp3"
title = "Nasty [WV53GyfJN0M]"

[[track]]
path = "/home/berni/Music/dj/Our Song [qDl0JqNBTxM].mp3"
title = "Our Song [qDl0JqNBTxM]"

[[track]]
path = "/home/berni/Music/dj/Overlook [B41PfcJ6FSY].mp3"
title = "Overlook [B41PfcJ6FSY]"

[[track]]
path = "/home/berni/Music/dj/Ping Pong 303 [SQKkHW3tN3M].mp3"
title = "Ping Pong 303 [SQKkHW3tN3M]"

[[track]]
path = "/home/berni/Music/dj/Rave All Night [0AH__e-uL7k].mp3"
title = "Rave All Night [0AH__e-uL7k]"

[[track]]
path = "/home/berni/Music/dj/Rockets (Franck Remix) [7RsNByK57ZM].mp3"
title = "Rockets (Franck Remix) [7RsNByK57ZM]"

[[track]]
path = "/home/berni/Music/dj/Side To Side [80vmI5raDS0].mp3"
title = "Side To Side [80vmI5raDS0]"

[[track]]
path = "/home/berni/Music/dj/Tanzen [vEzVh2OlFQw].mp3"
title = "Tanzen [vEzVh2OlFQw]"

[[track]]
path = "/home/berni/Music/dj/Turn It Up [9jTlMgM-kuY].mp3"
title = "Turn It Up [9jTlMgM-kuY]"

[[track]]
path = "/home/berni/Music/dj/Vitamin C [T052qZWhnpY].mp3"
title = "Vitamin C [T052qZWhnpY]"

[[track]]
path = "/home/berni/Music/dj/What's a Girl to Do in '25 [RFDg8V1caUQ].mp3"
title = "What's a Girl to Do in '25 [RFDg8V1caUQ]"

[[track]]
path = "/home/berni/Music/dj/Winds (Feel for You) [IfUK0lo7nrI].mp3"
title = "Winds (Feel for You) [IfUK0lo7nrI]"

[[track]]
path = "/home/berni/Music/dj/ÜBERHOLSPUR [_tfdPPEDinM].mp3"
title = "ÜBERHOLSPUR [_tfdPPEDinM]"

[[track]]
path = "/home/berni/Music/dj/ЗАВОД [hssSTXMcyBQ].mp3"
title = "ЗАВОД [hssSTXMcyBQ]"
