background = #010101
foreground = #cdd6f4
background-opacity = 0.4

cursor-color = #39c5bb
cursor-text = #010101

selection-background = #39c5bb
selection-foreground = #010101

palette = 0=#45475a
palette = 1=#f38ba8
palette = 2=#a6e3a1
palette = 3=#f9a8d4
palette = 4=#38bdf8
palette = 5=#39c5bb
palette = 6=#94e2d5
palette = 7=#bac2de
palette = 8=#585b70
palette = 9=#f38ba8
palette = 10=#72efdd
palette = 11=#f9a8d4
palette = 12=#38bdf8
palette = 13=#39c5bb
palette = 14=#94e2d5
palette = 15=#a6adc8
palette = 16=#f9a8d4
palette = 17=#39c5bb
