# DP-3: external, portrait (90 CCW), left side
monitor=DP-3,1920x1080@100,0x0,1.0,transform,1

# eDP-1: laptop screen, positioned to the right of DP-3 in portrait (effective width 1080px)
monitor=eDP-1,2880x1800@120,1274x1696,1.34

# 2k Monitor above
monitor=HDMI-A-1,2560x1440@100.0,1080x256,1.0

# Fallback for any other monitor
monitor=,preferred,auto,1
