[[entry]]
played_at = "2026-08-21T18:50:52Z"
path = "/home/berni/Music/勝つさ/Kataomoi [NFHPLE4Tl0I].mp3"
title = "Kataomoi [NFHPLE4Tl0I]"

[[entry]]
played_at = "2026-08-17T21:48:57Z"
path = "/home/berni/Music/中文/寂寞烟火 [6U_v5p8SyW4].mp3"
title = "寂寞烟火 [6U_v5p8SyW4]"

[[entry]]
played_at = "2026-08-15T12:57:26Z"
path = "/home/berni/Music/dj/Knowledge is a weapon [QHi6SVJf2Fk].mp3"
title = "Knowledge is a weapon [QHi6SVJf2Fk]"

[[entry]]
played_at = "2026-08-15T12:18:25Z"
path = "/home/berni/Music/dj/LAMBORGHINI [3Tmn7AX-fM0].mp3"
title = "LAMBORGHINI [3Tmn7AX-fM0]"

[[entry]]
played_at = "2026-08-14T16:24:11Z"
path = "/home/berni/Music/中文/不醉不會 [ohoeAKGx9SE].mp3"
title = "不醉不會 [ohoeAKGx9SE]"

[[entry]]
played_at = "2026-08-11T00:34:26Z"
path = "/home/berni/Music/勝つさ/オルターエゴ [GkyGwZRo3kQ].mp3"
title = "オルターエゴ [GkyGwZRo3kQ]"

[[entry]]
played_at = "2026-08-10T23:13:42Z"
path = "/home/berni/Music/勝つさ/MoeChakkaFire [HqzDtn-cPas].mp3"
title = "MoeChakkaFire [HqzDtn-cPas]"

[[entry]]
played_at = "2026-08-10T01:27:32Z"
path = "/home/berni/Music/勝つさ/Headphone Actor [nnyACg_WQLw].mp3"
title = "Headphone Actor [nnyACg_WQLw]"

[[entry]]
played_at = "2026-08-10T00:23:50Z"
path = "/home/berni/Music/勝つさ/故にユーエンミー [R8AvnZFX4Xs].mp3"
title = "故にユーエンミー [R8AvnZFX4Xs]"

[[entry]]
played_at = "2026-07-24T20:24:33Z"
path = "/home/berni/Music/勝つさ/スポットレイト [0IdZLAOltls].mp3"
title = "スポットレイト [0IdZLAOltls]"

[[entry]]
played_at = "2026-07-24T19:50:01Z"
path = "/home/berni/Music/勝つさ/Hananikaze [rw2e0vpMw7E].mp3"
title = "Hananikaze [rw2e0vpMw7E]"

[[entry]]
played_at = "2026-07-24T19:38:46Z"
path = "/home/berni/Music/勝つさ/おどれ! VRダンス! [9cOltK14h54].mp3"
title = "おどれ! VRダンス! [9cOltK14h54]"

[[entry]]
played_at = "2026-07-23T02:52:58Z"
path = "/home/berni/Music/勝つさ/米津玄師 - ピースサイン , Kenshi Yonezu - Peace Sign [9aJVr5tTTWk].mp3"
title = "ピースサイン , Kenshi Yonezu - Peace Sign [9aJVr5tTTWk]"
artist = "米津玄師"

[[entry]]
played_at = "2026-07-20T19:31:40Z"
path = "/home/berni/Music/勝つさ/【公式】 レミングミング／かいりきベア feat.flower [4oCuGeHWzCo].mp3"
title = "【公式】 レミングミング／かいりきベア feat.flower [4oCuGeHWzCo]"

[[entry]]
played_at = "2026-07-20T19:17:22Z"
path = "/home/berni/Music/勝つさ/うみたがり 【UTAUカバー】【松田っぽいよ】 [eKAl-TF1g4o].mp3"
title = "うみたがり 【UTAUカバー】【松田っぽいよ】 [eKAl-TF1g4o]"

[[entry]]
played_at = "2026-07-20T18:43:39Z"
path = "/home/berni/Music/勝つさ/Bareru! [GSr2LPG4OXs].mp3"
title = "Bareru! [GSr2LPG4OXs]"

[[entry]]
played_at = "2026-07-16T14:49:47Z"
path = "/home/berni/Music/勝つさ/稲葉曇『電気予報』feat. 初音ミク [Imcr7rsBxsc].mp3"
title = "稲葉曇『電気予報』feat. 初音ミク [Imcr7rsBxsc]"

[[entry]]
played_at = "2026-07-16T01:47:09Z"
path = "/home/berni/Music/勝つさ/ストロボライト [tfU5hYh6oVQ].mp3"
title = "ストロボライト [tfU5hYh6oVQ]"

[[entry]]
played_at = "2026-07-12T16:56:50Z"
path = "/home/berni/Music/勝つさ/頭ん中DEAD END [qwmWTVp-9S8].mp3"
title = "頭ん中DEAD END [qwmWTVp-9S8]"

[[entry]]
played_at = "2026-07-10T03:13:28Z"
path = "/home/berni/Music/勝つさ/If I could be a constellation [-LwBbLa_Vhc].mp3"
title = "If I could be a constellation [-LwBbLa_Vhc]"

[[entry]]
played_at = "2026-06-28T21:24:58Z"
path = "http://radio.cliamp.stream/lofi/stream"
title = "Lofi Stream"

[[entry]]
played_at = "2026-06-28T16:21:56Z"
path = "/home/berni/Music/dj/Nasty [WV53GyfJN0M].mp3"
title = "Nasty [WV53GyfJN0M]"

[[entry]]
played_at = "2026-06-28T13:41:08Z"
path = "/home/berni/Music/勝つさ/＊ハロー、プラネット。 [12puesDWfeo].mp3"
title = "＊ハロー、プラネット。 [12puesDWfeo]"

[[entry]]
played_at = "2026-06-28T01:59:23Z"
path = "/home/berni/Music/勝つさ/【MV】ブレス／まふまふ×DECO＊27 [Mgxx8E--PwY].mp3"
title = "【MV】ブレス／まふまふ×DECO＊27 [Mgxx8E--PwY]"

[[entry]]
played_at = "2026-06-27T20:51:42Z"
path = "/home/berni/Music/勝つさ/爆裂愛してる [20bYUQZOAeQ].mp3"
title = "爆裂愛してる [20bYUQZOAeQ]"

[[entry]]
played_at = "2026-06-27T20:27:32Z"
path = "/home/berni/Music/勝つさ/Silly [efGF_1EQalE].mp3"
title = "Silly [efGF_1EQalE]"

[[entry]]
played_at = "2026-06-26T23:32:56Z"
path = "/home/berni/Music/勝つさ/Bon Appetit S [6nVXFuKkHoU].mp3"
title = "Bon Appetit S [6nVXFuKkHoU]"

[[entry]]
played_at = "2026-06-22T16:23:13Z"
path = "/home/berni/Music/勝つさ/パノプティコン 2021 [9J_UVrL6Z-c].mp3"
title = "パノプティコン 2021 [9J_UVrL6Z-c]"

[[entry]]
played_at = "2026-06-22T03:43:35Z"
path = "/home/berni/Music/勝つさ/× [vwxv0OKyu5c].mp3"
title = "× [vwxv0OKyu5c]"

[[entry]]
played_at = "2026-06-22T03:37:08Z"
path = "/home/berni/Music/勝つさ/Kan Saete Kuyashiiwa [TRdnYZtnNis].mp3"
title = "Kan Saete Kuyashiiwa [TRdnYZtnNis]"

[[entry]]
played_at = "2026-06-22T03:31:20Z"
path = "/home/berni/Music/勝つさ/Kan Saete Kuyashiiwa [TRdnYZtnNis].mp3"
title = "Kan Saete Kuyashiiwa [TRdnYZtnNis]"

[[entry]]
played_at = "2026-06-22T03:12:57Z"
path = "/home/berni/Music/勝つさ/シリーテラー (feat. IA) [EWAXsIpWmaw].mp3"
title = "シリーテラー (feat. IA) [EWAXsIpWmaw]"

[[entry]]
played_at = "2026-06-22T03:00:21Z"
path = "/home/berni/Music/勝つさ/ホワイトハッピー\u3000歌ってみた ⧸ 雨乃こさめ(cover) [gS4rJLTv1RQ].mp3"
title = "ホワイトハッピー\u3000歌ってみた ⧸ 雨乃こさめ(cover) [gS4rJLTv1RQ]"

[[entry]]
played_at = "2026-06-22T02:50:52Z"
path = "/home/berni/Music/勝つさ/全部壊しちゃえ！ [u0LszndVXcw].mp3"
title = "全部壊しちゃえ！ [u0LszndVXcw]"

[[entry]]
played_at = "2026-06-22T02:48:52Z"
path = "/home/berni/Music/勝つさ/ピコン - ガランド ft. 初音ミク [SXC2wO1XdMI].mp3"
title = "ガランド ft. 初音ミク [SXC2wO1XdMI]"
artist = "ピコン"

[[entry]]
played_at = "2026-06-21T01:36:42Z"
path = "/home/berni/Music/勝つさ/ゴー・トゥ・大都会 (feat. GUMI) [xfGOV5krV0M].mp3"
title = "ゴー・トゥ・大都会 (feat. GUMI) [xfGOV5krV0M]"

[[entry]]
played_at = "2026-06-20T17:52:15Z"
path = "/home/berni/Music/勝つさ/しう [D2NBIvZH6hU].mp3"
title = "しう [D2NBIvZH6hU]"

[[entry]]
played_at = "2026-06-18T22:23:59Z"
path = "/home/berni/Music/勝つさ/TAKE OFF [_obXLr57EQE].mp3"
title = "TAKE OFF [_obXLr57EQE]"

[[entry]]
played_at = "2026-06-18T03:32:50Z"
path = "/home/berni/Music/勝つさ/ロータスイーター (feat. 歌愛ユキ) [NmSqe3M-6MY].mp3"
title = "ロータスイーター (feat. 歌愛ユキ) [NmSqe3M-6MY]"

[[entry]]
played_at = "2026-06-16T18:26:29Z"
path = "/home/berni/Music/勝つさ/愛して愛して愛して 歌ってみた ⧸Love Me, Love Me, Love Me (Cover) [Q-HpvIo5fCA].mp3"
title = "愛して愛して愛して 歌ってみた ⧸Love Me, Love Me, Love Me (Cover) [Q-HpvIo5fCA]"

[[entry]]
played_at = "2026-06-15T16:29:20Z"
path = "/home/berni/Music/勝つさ/ATELIER [J_vEyOEo2sI].mp3"
title = "ATELIER [J_vEyOEo2sI]"

[[entry]]
played_at = "2026-06-14T02:30:19Z"
path = "/home/berni/Music/勝つさ/少女A [JqO33QER3LI].mp3"
title = "少女A [JqO33QER3LI]"

[[entry]]
played_at = "2026-06-13T04:24:06Z"
path = "/home/berni/Music/勝つさ/Sakayume [9y5iaRtS3hU].mp3"
title = "Sakayume [9y5iaRtS3hU]"

[[entry]]
played_at = "2026-06-10T03:43:30Z"
path = "/home/berni/Music/勝つさ/わたしは禁忌 [Xd2SQ0pK2aU].mp3"
title = "わたしは禁忌 [Xd2SQ0pK2aU]"

[[entry]]
played_at = "2026-06-09T22:25:27Z"
path = "/home/berni/Music/勝つさ/自由のショート [UssGf4jvX38].mp3"
title = "自由のショート [UssGf4jvX38]"

[[entry]]
played_at = "2026-06-09T00:52:48Z"
path = "/home/berni/Music/勝つさ/Matoryoshka (ORIGINAL) [13OUbaozM9o].mp3"
title = "Matoryoshka (ORIGINAL) [13OUbaozM9o]"

[[entry]]
played_at = "2026-06-08T01:48:45Z"
path = "/home/berni/Music/勝つさ/+♂ver れをる [6HGLeUqoUf8].mp3"
title = "+♂ver れをる [6HGLeUqoUf8]"

[[entry]]
played_at = "2026-06-06T21:02:48Z"
path = "/home/berni/Music/勝つさ/恋 [KMdTrqzEI0I].mp3"
title = "恋 [KMdTrqzEI0I]"

[[entry]]
played_at = "2026-06-06T20:47:00Z"
path = "/home/berni/Music/勝つさ/海色 [W6zK9jCf5sM].mp3"
title = "海色 [W6zK9jCf5sM]"

[[entry]]
played_at = "2026-06-06T20:32:30Z"
path = "/home/berni/Music/勝つさ/【Ci flower】全部夢だった！【VoiSona Cover】 [G7Z4xGh92bI].mp3"
title = "【Ci flower】全部夢だった！【VoiSona Cover】 [G7Z4xGh92bI]"

[[entry]]
played_at = "2026-06-04T04:45:10Z"
path = "/home/berni/Music/勝つさ/Je t'aime Je t'aime [CdezOrDdyW0].mp3"
title = "Je t'aime Je t'aime [CdezOrDdyW0]"

[[entry]]
played_at = "2026-06-04T03:02:55Z"
path = "/home/berni/Music/勝つさ/Spider Dance [NH-GAwLAO30].mp3"
title = "Spider Dance [NH-GAwLAO30]"

[[entry]]
played_at = "2026-06-03T04:16:16Z"
path = "/home/berni/Music/勝つさ/キライ・キライ・ジガヒダイ! [YSWkehiqMlE].mp3"
title = "キライ・キライ・ジガヒダイ! [YSWkehiqMlE]"

[[entry]]
played_at = "2026-06-01T18:38:19Z"
path = "/home/berni/Music/勝つさ/Neru - ロストワンの号哭(Lost One's Weeping) feat. Kagamine Rin [8oBV3jPTW4s].mp3"
title = "ロストワンの号哭(Lost One's Weeping) feat. Kagamine Rin [8oBV3jPTW4s]"
artist = "Neru"

[[entry]]
played_at = "2026-06-01T17:28:10Z"
path = "/home/berni/Music/勝つさ/聖槍爆裂ボーイ - れるりりfeat.鏡音レン ⧸ Holy Lance Explosion Boy - rerulili feat.KagamineLen [MqNmKnCNLyM].mp3"
title = "れるりりfeat.鏡音レン ⧸ Holy Lance Explosion Boy - rerulili feat.KagamineLen [MqNmKnCNLyM]"
artist = "聖槍爆裂ボーイ"

[[entry]]
played_at = "2026-05-31T22:15:48Z"
path = "http://radio.cliamp.stream/lofi/stream"
title = "Lofi Stream"

[[entry]]
played_at = "2026-05-31T21:30:04Z"
path = "/home/berni/Music/勝つさ/ホワイトハッピー [Ltm2eAX6PPw].mp3"
title = "ホワイトハッピー [Ltm2eAX6PPw]"

[[entry]]
played_at = "2026-05-31T19:42:42Z"
path = "/home/berni/Music/勝つさ/腐りきった人生だ。⧸ たかやん (Official Music Video) [za8FiI0WH5g].mp3"
title = "腐りきった人生だ。⧸ たかやん (Official Music Video) [za8FiI0WH5g]"

[[entry]]
played_at = "2026-05-31T03:37:28Z"
path = "/home/berni/Music/勝つさ/アングレイデイズ [4qN2aktWA1Y].mp3"
title = "アングレイデイズ [4qN2aktWA1Y]"

[[entry]]
played_at = "2026-05-31T00:14:09Z"
path = "/home/berni/Music/勝つさ/アングレイデイズ [4qN2aktWA1Y].mp3"
title = "アングレイデイズ [4qN2aktWA1Y]"

[[entry]]
played_at = "2026-05-30T19:17:59Z"
path = "/home/berni/Music/勝つさ/Ai No Meiwaku [XX_lYZVlNQI].mp3"
title = "Ai No Meiwaku [XX_lYZVlNQI]"

[[entry]]
played_at = "2026-05-29T20:39:18Z"
path = "/home/berni/Music/勝つさ/HUMANLIKE [KWy0e3uXsvg].mp3"
title = "HUMANLIKE [KWy0e3uXsvg]"

[[entry]]
played_at = "2026-05-28T05:43:20Z"
path = "https://play.streamafrica.net/japancitypop"
title = "BOX : Japan City Pop - 日本のシティポップ"

[[entry]]
played_at = "2026-05-27T04:57:02Z"
path = "/home/berni/Music/勝つさ/コインロッカーベイビー [RgHTSrw82GQ].mp3"
title = "コインロッカーベイビー [RgHTSrw82GQ]"

[[entry]]
played_at = "2026-05-25T00:54:55Z"
path = "/home/berni/Music/勝つさ/Que Sera Sera [s4ZThuWQdhA].mp3"
title = "Que Sera Sera [s4ZThuWQdhA]"

[[entry]]
played_at = "2026-05-24T22:18:38Z"
path = "/home/berni/Music/dj/All Eyes On Me [9HeiBJ5mgtA].mp3"
title = "All Eyes On Me [9HeiBJ5mgtA]"

[[entry]]
played_at = "2026-05-24T20:58:22Z"
path = "https://live.top-media.al/tar"
title = "Top Albanian Radio"

[[entry]]
played_at = "2026-05-24T20:58:18Z"
path = "chunks.m3u8?nimblesessionid=851987941"
title = "chunks"

[[entry]]
played_at = "2026-05-24T19:28:02Z"
path = "/home/berni/Music/勝つさ/少女レイ (feat. 桐谷遥 & 日野森雫 & 初音ミク) [UoPx7M5pZxw].mp3"
title = "少女レイ (feat. 桐谷遥 & 日野森雫 & 初音ミク) [UoPx7M5pZxw]"

[[entry]]
played_at = "2026-05-21T23:30:20Z"
path = "/home/berni/Music/勝つさ/エイリアンエイリアン (feat. 鳳えむ & 草薙寧々 & 初音ミク) [ghQmxBFLas0].mp3"
title = "エイリアンエイリアン (feat. 鳳えむ & 草薙寧々 & 初音ミク) [ghQmxBFLas0]"

[[entry]]
played_at = "2026-05-21T22:32:58Z"
path = "/home/berni/Music/勝つさ/ユメウツツ空想論 [NifZhiHlHok].mp3"
title = "ユメウツツ空想論 [NifZhiHlHok]"

[[entry]]
played_at = "2026-05-19T00:05:43Z"
path = "/home/berni/Music/中文/一点点 (DJ版) [Ke-xD5_3tGY].mp3"
title = "一点点 (DJ版) [Ke-xD5_3tGY]"

[[entry]]
played_at = "2026-05-16T14:31:47Z"
path = "/home/berni/Music/勝つさ/Beautiful Fin [n2m9ebS3tEo].mp3"
title = "Beautiful Fin [n2m9ebS3tEo]"

[[entry]]
played_at = "2026-05-16T04:09:14Z"
path = "/home/berni/Music/勝つさ/Matsuri [HMqhXxH5-RQ].mp3"
title = "Matsuri [HMqhXxH5-RQ]"

[[entry]]
played_at = "2026-05-16T03:55:41Z"
path = "/home/berni/Music/勝つさ/ON AND ON [rt5682MtBv4].mp3"
title = "ON AND ON [rt5682MtBv4]"

[[entry]]
played_at = "2026-05-16T03:28:31Z"
path = "/home/berni/Music/dj/Side To Side [80vmI5raDS0].mp3"
title = "Side To Side [80vmI5raDS0]"

[[entry]]
played_at = "2026-05-16T03:01:18Z"
path = "/home/berni/Music/勝つさ/ZERO ICHI [-yGI2uFaacY].mp3"
title = "ZERO ICHI [-yGI2uFaacY]"

[[entry]]
played_at = "2026-05-15T21:05:01Z"
path = "/home/berni/Music/勝つさ/ダウンタイマー [Zyr_oflgW64].mp3"
title = "ダウンタイマー [Zyr_oflgW64]"

[[entry]]
played_at = "2026-05-15T20:12:03Z"
path = "/home/berni/Music/勝つさ/Blow [kGvAkFmLWYM].mp3"
title = "Blow [kGvAkFmLWYM]"

[[entry]]
played_at = "2026-05-15T19:57:29Z"
path = "/home/berni/Music/勝つさ/Happy Birthday!!! [vR3QinTtynI].mp3"
title = "Happy Birthday!!! [vR3QinTtynI]"

[[entry]]
played_at = "2026-05-15T02:54:47Z"
path = "/home/berni/Music/勝つさ/Hanaichi Monnme [Db7sdFPSgR0].mp3"
title = "Hanaichi Monnme [Db7sdFPSgR0]"

[[entry]]
played_at = "2026-05-14T23:32:38Z"
path = "/home/berni/Music/勝つさ/恋愛裁判 [_CovcE8LQjU].mp3"
title = "恋愛裁判 [_CovcE8LQjU]"

[[entry]]
played_at = "2026-05-14T23:17:29Z"
path = "/home/berni/Music/勝つさ/明星ギャラクティカ [6wETrzAiCJ8].mp3"
title = "明星ギャラクティカ [6wETrzAiCJ8]"

[[entry]]
played_at = "2026-05-14T22:14:43Z"
path = "/home/berni/Music/勝つさ/DONUT HOLE [nJfaXyDLwy4].mp3"
title = "DONUT HOLE [nJfaXyDLwy4]"

[[entry]]
played_at = "2026-05-14T22:11:59Z"
path = "/home/berni/Music/勝つさ/DEAD WEIGHT [UHlScHFWAlA].mp3"
title = "DEAD WEIGHT [UHlScHFWAlA]"

[[entry]]
played_at = "2026-05-14T21:46:13Z"
path = "/home/berni/Music/勝つさ/Koibito Boshuuchuu (Kari) [34GJbSywPO4].mp3"
title = "Koibito Boshuuchuu (Kari) [34GJbSywPO4]"

[[entry]]
played_at = "2026-05-14T03:16:30Z"
path = "/home/berni/Music/中文/Coco Elva Tia [JXb04PcA7rg].mp3"
title = "Coco Elva Tia [JXb04PcA7rg]"

[[entry]]
played_at = "2026-05-14T03:11:53Z"
path = "/home/berni/Music/勝つさ/Ignite [XXV6oIory8s].mp3"
title = "Ignite [XXV6oIory8s]"

[[entry]]
played_at = "2026-05-12T16:50:45Z"
path = "/home/berni/Music/メンタルチェンソー [tr0fW92PIc8].mp3"
title = "メンタルチェンソー [tr0fW92PIc8]"

[[entry]]
played_at = "2026-05-12T16:08:38Z"
path = "/home/berni/Music/Ai No Meiwaku [XX_lYZVlNQI].mp3"
title = "Ai No Meiwaku [XX_lYZVlNQI]"

[[entry]]
played_at = "2026-05-12T16:06:04Z"
path = "/home/berni/Music/超常現象ダンスダンス [hsmFEod1EXU].mp3"
title = "超常現象ダンスダンス [hsmFEod1EXU]"

[[entry]]
played_at = "2026-05-12T15:03:05Z"
path = "/home/berni/Music/ビビビビ [VWacsD8ItB0].mp3"
title = "ビビビビ [VWacsD8ItB0]"

[[entry]]
played_at = "2026-05-12T06:01:23Z"
path = "/home/berni/Music/稲葉曇『秘密音楽』Vo. 歌愛ユキ [sXc204xHj8g].mp3"
title = "稲葉曇『秘密音楽』Vo. 歌愛ユキ [sXc204xHj8g]"

[[entry]]
played_at = "2026-05-12T05:43:02Z"
path = "/home/berni/Music/ことなる Way - Dreaming Of You [L8swPiwzt7c].mp3"
title = "Dreaming Of You [L8swPiwzt7c]"
artist = "ことなる Way"
