[[entry]]
played_at = "2026-08-30T16:31:18Z"
path = "/home/berni/Music/勝つさ/Neru - テロル(Terror) feat. Kagamine Rin [rePFEUu7YZs].mp3"
title = "テロル(Terror) feat. Kagamine Rin [rePFEUu7YZs]"
artist = "Neru"

[[entry]]
played_at = "2026-08-30T04:15:47Z"
path = "/home/berni/Music/勝つさ/パノプティコン 2021 [9J_UVrL6Z-c].mp3"
title = "パノプティコン 2021 [9J_UVrL6Z-c]"
duration_secs = 262

[[entry]]
played_at = "2026-08-28T19:40:09Z"
path = "/home/berni/Music/中文/Jumping Machine (跳楼机) [TOC78RUj8pg].mp3"
title = "Jumping Machine (跳楼机) [TOC78RUj8pg]"
duration_secs = 201

[[entry]]
played_at = "2026-08-28T19:36:47Z"
path = "/home/berni/Music/中文/Illusionary Daytime (幻奏 Remix) [hATE0C4aQqw].mp3"
title = "Illusionary Daytime (幻奏 Remix) [hATE0C4aQqw]"
duration_secs = 130
