general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono" }
bold = { family = "CaskaydiaCove Nerd Font Mono" }
italic = { family = "CaskaydiaCove Nerd Font Mono" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.65

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
